#pragma once

enum EventType{
    EVT_UNKOWN,
    EVT_QUOTE,
    EVT_ORDER,
    EVT_POSITION,
    EVT_RPT_ORDER_NEW_DONE,
    EVT_RPT_ORDER_NEW_REJECT,
    EVT_RPT_ORDER_FILL,
    EVT_RPT_ORDER_CANCEL_DONE,
    EVT_RPT_ORDER_CANCEL_REJECT,
};